{
    "name": "Mejora de Lista de Precios 2",
    "summary": "Oncompetence Solutions",
    "description": "Mejora de Lista de Precios",
    "version": "18.0",
    "author": "Micaela Ortiz",
    "license": "AGPL-3",
    "depends": [
        "base",
        "stock",
        "sale",
        "sale_management",
        "account",
        "product",
        "product_replenishment_cost",
        "product_pricelist_improvement",
    ],
    "data": [
        "data/pricelist.xml",
        "views/item_pricelist_form_view.xml",
    ],
    "installable": True,
    "application": True,
    "auto_install": False,
}
