{
    "name": "Cupones de Pago",
    "version": "18.0",
    "description": "Permite gestionar cupones al momento de registrar un pago.",
    "category": "Accounting",
    "author": "Micaela Ortiz",
    "company": "Oncompetence",
    "website": "https://oncompetence.odoo.com/",
    "depends": [
        "base",
        "sale_management",
        "sale",
        "account",
        "account_accountant",
        "account_payment",
        "card_installment",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/account_payment_coupon_views.xml",
        "views/account_payment_views.xml",
        "views/account_card_views.xml",
    ],
    "installable": True,
    "auto_install": False,
    "application": True,
    "license": "LGPL-3",
}
